spring.application.name=bookbank-backend
spring.datasource.url=jdbc:mysql://localhost:3306/bookbank
spring.datasource.username=USERNAME
spring.datasource.password=PASSWORD

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=JSW_SECRET